trigger: none

resources:
  repositories:
  - repository: baseline_project_repo
    name: DevOps/_git/devops-common-utils
    type: git
    ref: feature/fix-python-build-promotion

pool:
  vmImage: ubuntu-latest

name: $(mybuildID)

variables:
- group: runner_Runner-AI
- name: containerRegistrySC
  value: ACR_Cargoes Runner


- name: mybuildID
  value: $[variables.buildID]

steps:
  - checkout: self #my_current_repo
    path: s
    displayName: 'Checking out my_current_repo'

  - checkout: baseline_project_repo
    displayName: Cheking baseline_project_repo

  - template: /pipelines/ci_build_promotion.yaml@baseline_project_repo